### ISSUE TITLE
Capitalized "UNITED STATES"

### ISSUE THREAD

**Issue by saiichihashimoto** [joaocarmo/i18n-postal-address#11]
Looking through the formats, the only capitalized country is United States. This isn't a convention in the US (as far as I know) and, as a default for a lot of apps, it's strange to have constantly have "UNITED STATES", especially when other countries will not be like this.

**Comment by joaocarmo** [comment]
@saiichihashimoto , I've following [this document](https://docs.microsoft.com/en-us/previous-versions/cc195167(v=msdn.10)) from Microsoft as a basis for the included formats which, regarding the US,  states:

> Note: The name of the country is in capital letters.

If you can provide me some other source of information regarding this, I'd gladly update the default formatting. I admit the decision to default countries without a format to the US format was completely arbitrary, but one had to be made.

I've been meaning to add a feature to the public API that allows custom formats. I may take this issue as a good enough reason to work on that.

**Comment by saiichihashimoto** [comment]
I understand the decision to follow standards and I agree its the correct way to go but, since most users likely use this for their production apps, having a custom format would be ideal.

**Comment by joaocarmo** [comment]
@saiichihashimoto , I've been working on this and I've added the new feature which allows adding or replacing formats with custom ones. You can check the documentation [here](https://github.com/joaocarmo/i18n-postal-address#custom-formats). Will make a new release for this later today.
