### ISSUE TITLE
Latin America: firstLastName, secondLastName and lastName

### ISSUE THREAD

**Issue by tn819** [joaocarmo/i18n-postal-address#155]
### Expected Behavior

I am invoking the below formatting for a generic address that could be from many countries, and getting unexpected results with Latin America/Spain where I have not specified `firstLastName` or `secondLastName`. 

In the code, I see we invoke on `setLastName`:
```
    this.setProperty('secondLastName', newValue)
```
which feels rather tricky.

I would expect if neither `firstLastName` or `secondLastName` is specified that we would assign no value to `secondLastName.`

### Actual Behavior
`setLastName` also sets `secondLastName`

### Steps to Reproduce
 ``` 
  postalAddress.setFormat({ country: 'ES' });

  postalAddress
    .setFirstName(firstName)
    .setLastName(lastName)
    .setCompanyName(company)
    .setAddress1(street)
    .setAddress2(addition)
    .setRegion(region) // region will be state in some locales, both don't seem to show at the same time so we pass to both
    .setState(region)
    .setPostalCode(zip)
    .setCity(place)
    .setCountry('Spain');
```
### Your Environment

not related to code

**Comment by tn819** [comment]
My current workaround is a check if countryCode is from Latin America, and then this specification:
```
if (['AR', 'ES'...#all latin american countries sparing for brevity].includes(countryCode)) {
    postalAddress.setFirstLastName(lastName).setSecondLastName(''); // required as for Spain and Latin America, lastName will be assigned to secondLastName on next line unless we unassign it here
  }
```

**Comment by joaocarmo** [comment]
In order to keep it backwards compatible, I've decided to add a feature to disable such propagations in #172.
