### ISSUE TITLE
addCommaAfter on custom format

### ISSUE THREAD

**Issue by minro** [joaocarmo/i18n-postal-address#16]
Hi, 
I'm trying to fetch a custom format from the server and apply it with transforms, something like this:

```
address.addFormat({
  country: addressData.countryCode,
  // this is my array of arrays from the server
  format: [["city", {"attribute": "postalCode", "transforms": ["addCommaAfter"]}]] 
  parser: "array",
  type: addressType
})

   // when I set the format I have also included:
.setFormat({
   country: addressData.countryCode,
   type: addressType,
   useTransforms: true
})
```

I seem unable to get commas to show up, perhaps this scenario isn't supported? or is this just the wrong approach?

**Comment by joaocarmo** [comment]
@minro , the `transforms` options accepts an **array** of **functions** that will be applied to the respective **attribute** in order having the current value as the only argument.

That could be as simple as:

```js
const addCommaAfter = (value) => `${value},`

address.addFormat({
  country: addressData.countryCode,
  // just remove the quotes and you're good to go
  format: [["city", {"attribute": "postalCode", "transforms": [addCommaAfter]}]] 
  parser: "array",
  type: addressType
})
```

Hope this helps!

**Comment by minro** [comment]
Thanks for the quick reply!

However I don't think it will, I'm sending the format from the server as a string and run it through JSON.parse() and the parser won't accept `[addCommaAfter]` without quotes.

I guess there's always the manual approach to fix that, but I'll give it another go in the morning. 
Thanks again!

**Comment by joaocarmo** [comment]
I guess your could make it an anonymous functions and serialize it, but you'd have to `eval()` it on the other side. See [this comment](https://stackoverflow.com/a/6755052/8713532) on _StackOverflow_, though it's not something I would recommend.

```js
address.addFormat({
  country: addressData.countryCode,
  // as an inline anonymous function
  format: [["city", {"attribute": "postalCode", "transforms": [v => v + ',']}]],
  parser: "array",
  type: addressType,
})
```
