### ISSUE TITLE
Types aren't a module

### ISSUE THREAD

**Issue by saiichihashimoto** [joaocarmo/i18n-postal-address#17]
Looking into v0.4.1's typings in `i18n-postal-address/dist/postal-address.d.ts`, it declares a lot of modules, none of them 18n-postal-address.

![image](https://user-images.githubusercontent.com/2819256/105655510-cbee8580-5e85-11eb-9f67-5230b943ac40.png)

Attempting to use the module in typescript fails, since the typings aren't a module.

![image](https://user-images.githubusercontent.com/2819256/105655653-11ab4e00-5e86-11eb-9757-66a7185915ba.png)

**Comment by joaocarmo** [comment]
@saiichihashimoto thank you for bringing this to my attention. #18 should fix this issue as of `v0.4.2`.
