### ISSUE TITLE
Wrong default for Canada

### ISSUE THREAD

**Issue by chbusch** [joaocarmo/i18n-postal-address#2]
Default for Sweden in address-formats.js is actually applied to Canada, resulting in error when canadian address specified without options.

address-formats.js, line 460
// Set Sweden's default to the personal format
addressFormats.CA.default = addressFormats.CA.personal

**Comment by joaocarmo** [comment]
Hi @chbusch ! Thank you for letting me know of this issue, I'll release a fix later today.

**Comment by chbusch** [comment]
Thanks!

**Comment by joaocarmo** [comment]
I just released `v0.0.7` which should address this issue, plus another in the lines above for Norway (NO). Let me know if you find any other issue, @chbusch !
