### ISSUE TITLE
Allow adding custom format for countries not supported by default in library

### ISSUE THREAD

**Issue by krarjun90** [joaocarmo/i18n-postal-address#38]
### Expected Behavior

Should format address for a country not supported by library with a newly added format 

### Actual Behavior

Formatting address with a new country (lets say GB) is not happening as the default list does not include GB

### Steps to Reproduce

Add a custom format for "GB". Set address and invoke toArray() / toString(). It will use a default format and not the custom added format for GB. 

`const address = new PostalAddress().addFormat({
    country: 'GB',
    format: [
      ['address1'],
      ['city', 'postalCode'],
    ],
    type: 'personal',
  })`

**Comment by joaocarmo** [comment]
@krarjun90 thank you for submitting this bug report!

The fix should be released with version `0.6.1`.

Don't forget to also set the format after adding the new format:

```js
const myCustomAddress = new PostalAddress().addFormat({
  country: 'GB',
  format: [
    ['address1'],
    ['city', 'postalCode'],
  ],
  type: 'personal',
}).setFormat({
  country: 'GB',
  type: 'personal',
})
```

**Comment by krarjun90** [comment]
@joaocarmo  thanks for the quick feedback 🥇  i was about to raise a PR myself  :)

regarding the release 0.6.1, do we have an ETA ?

**Comment by joaocarmo** [comment]
I really appreciate that! This has just been published, so let me know if you find any other issue.
