### ISSUE TITLE
US address missing comma after city

### ISSUE THREAD

**Issue by kboedges** [joaocarmo/i18n-postal-address#8]
```
const myAddressPersonal = new PostalAddress();

myAddressPersonal
    .setAddress1('123 Nevermore Rd')
    .setCity('Austin')
    .setState('TX')
    .setPostalCode('78752')
    .setOutputFormat('array')
    .setFormat({
        country: 'US',
        type: 'personal',
        useTransforms: false,
    })
    .toString();
```

## This returns
123 Nevermore Rd
Austin TX 78752

## Instead of
123 Nevermore Rd
Austin, TX 78752

Are commas and other punctuation left out intentionally?

**Comment by joaocarmo** [comment]
For now, commas and other punctuation are not taken into consideration.

As you can see for this Microsoft [documentation][ms-doc], some countries (e.g., Australia, Turkey, United States) do have some punctuation (e.g., comma after \<City\>, comma after \<PostalCode\>) as a standard.

I believe we could solve this easily by adding an `addComma()` [address transform][address-transform] function and include it in the transforms property of the affected [address format][address-format].

Feel free to submit a PR for this!



[ms-doc]: https://docs.microsoft.com/en-us/previous-versions/cc195167(v=msdn.10)
[address-transform]: https://github.com/joaocarmo/i18n-postal-address/blob/master/lib/address-transforms.ts
[address-format]: https://github.com/joaocarmo/i18n-postal-address/blob/master/lib/address-formats.ts#L404

**Comment by joaocarmo** [comment]
@kboedges , the next release will include the updated definitions which add commas in certain formats. You do need to enable the `useTransforms: true` flag (its default value).
